<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261003185350 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, url VARCHAR(2048) NOT NULL, display_order INT DEFAULT 0 NOT NULL, game_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DDB9F5DDE48FD905 ON game_link (game_id)');
        $this->addSql('ALTER TABLE game_link ADD CONSTRAINT FK_DDB9F5DDE48FD905 FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game DROP itch_url');
        $this->addSql('ALTER TABLE game DROP steam_url');
        $this->addSql('ALTER TABLE game DROP epic_url');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_link DROP CONSTRAINT FK_DDB9F5DDE48FD905');
        $this->addSql('DROP TABLE game_link');
        $this->addSql('ALTER TABLE game ADD itch_url VARCHAR(2048) DEFAULT NULL');
        $this->addSql('ALTER TABLE game ADD steam_url VARCHAR(2048) DEFAULT NULL');
        $this->addSql('ALTER TABLE game ADD epic_url VARCHAR(2048) DEFAULT NULL');
    }
}
