<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261003195922 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE jam (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, mode VARCHAR(20) NOT NULL, permanent BOOLEAN DEFAULT false NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, source_name VARCHAR(160) NOT NULL, source_url VARCHAR(2048) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE jam_schedule_day (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jam_date DATE NOT NULL, theme_label VARCHAR(120) NOT NULL, color1 VARCHAR(7) NOT NULL, color2 VARCHAR(7) NOT NULL, color3 VARCHAR(7) NOT NULL, jam_id INT NOT NULL, theme_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CCED5536ECB3E09E ON jam_schedule_day (jam_id)');
        $this->addSql('CREATE INDEX IDX_CCED553659027487 ON jam_schedule_day (theme_id)');
        $this->addSql('CREATE TABLE jam_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jam_date DATE NOT NULL, theme_label VARCHAR(120) NOT NULL, color1 VARCHAR(7) NOT NULL, color2 VARCHAR(7) NOT NULL, color3 VARCHAR(7) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, jam_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8BDB9D2DECB3E09E ON jam_session (jam_id)');
        $this->addSql('CREATE TABLE jam_theme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_75EB38A35E237E06 ON jam_theme (name)');
        $this->addSql('ALTER TABLE jam_schedule_day ADD CONSTRAINT FK_CCED5536ECB3E09E FOREIGN KEY (jam_id) REFERENCES jam (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE jam_schedule_day ADD CONSTRAINT FK_CCED553659027487 FOREIGN KEY (theme_id) REFERENCES jam_theme (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE jam_session ADD CONSTRAINT FK_8BDB9D2DECB3E09E FOREIGN KEY (jam_id) REFERENCES jam (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE jam_schedule_day DROP CONSTRAINT FK_CCED5536ECB3E09E');
        $this->addSql('ALTER TABLE jam_schedule_day DROP CONSTRAINT FK_CCED553659027487');
        $this->addSql('ALTER TABLE jam_session DROP CONSTRAINT FK_8BDB9D2DECB3E09E');
        $this->addSql('DROP TABLE jam');
        $this->addSql('DROP TABLE jam_schedule_day');
        $this->addSql('DROP TABLE jam_session');
        $this->addSql('DROP TABLE jam_theme');
    }
}
