<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261003143511 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE about (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, image_key VARCHAR(512) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE social_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, platform VARCHAR(50) NOT NULL, label VARCHAR(255) DEFAULT NULL, url VARCHAR(2048) NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, display_order INT DEFAULT 0 NOT NULL, about_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_79BD4A95D087DB59 ON social_link (about_id)');
        $this->addSql('ALTER TABLE social_link ADD CONSTRAINT FK_79BD4A95D087DB59 FOREIGN KEY (about_id) REFERENCES about (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE social_link DROP CONSTRAINT FK_79BD4A95D087DB59');
        $this->addSql('DROP TABLE about');
        $this->addSql('DROP TABLE social_link');
    }
}
