<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261003145131 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE site_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, brand_text VARCHAR(255) NOT NULL, blog_label VARCHAR(100) NOT NULL, blog_enabled BOOLEAN DEFAULT true NOT NULL, games_label VARCHAR(100) NOT NULL, games_enabled BOOLEAN DEFAULT true NOT NULL, about_label VARCHAR(100) NOT NULL, about_enabled BOOLEAN DEFAULT true NOT NULL, footer_text TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE site_settings');
    }
}
