<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261003160636 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE career_offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, display_order INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE faq_question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, display_order INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE site_social_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, platform VARCHAR(50) NOT NULL, url VARCHAR(2048) NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, display_order INT DEFAULT 0 NOT NULL, site_settings_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_92937525B2BAA738 ON site_social_link (site_settings_id)');
        $this->addSql('ALTER TABLE site_social_link ADD CONSTRAINT FK_92937525B2BAA738 FOREIGN KEY (site_settings_id) REFERENCES site_settings (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game ADD itch_url VARCHAR(2048) DEFAULT NULL');
        $this->addSql('ALTER TABLE game ADD steam_url VARCHAR(2048) DEFAULT NULL');
        $this->addSql('ALTER TABLE game ADD epic_url VARCHAR(2048) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD display_username VARCHAR(100) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE site_social_link DROP CONSTRAINT FK_92937525B2BAA738');
        $this->addSql('DROP TABLE career_offer');
        $this->addSql('DROP TABLE faq_question');
        $this->addSql('DROP TABLE site_social_link');
        $this->addSql('ALTER TABLE game DROP itch_url');
        $this->addSql('ALTER TABLE game DROP steam_url');
        $this->addSql('ALTER TABLE game DROP epic_url');
        $this->addSql('DROP INDEX UNIQ_8D93D649F85E0677');
        $this->addSql('ALTER TABLE "user" DROP display_username');
    }
}
